### PR TITLE
Update to use newer gcloud client, add result_storage class

### PR DESCRIPTION
**Pull request by BradWhittington**
This updates to a newer gcloud client, and pins upstream versions. It also adds a RESULT_STORAGE class to store transformed files into a google storage bucket.

### CODE REVIEW

**Comment by pedrogimenez** [comment]
Hi @BradWhittington, thank you for the PR. However, I no longer use this so I have no time to look at the changes you've introduced. I'll leave this here till I find some time to review it.

**Comment by BradWhittington** [comment]
@pedrogimenez happy to take over maintenance of the project, we're actively using it running a busy cluster of image servers, and I've effectively rewritten lots of the project....

**Comment by RuslanZavacky** [comment]
@BradWhittington is it possible to install your fork for thumbor?

**Comment by BradWhittington** [comment]
We're using it in production at the moment, installed as a pip dependency, @RuslanZavacky

**Comment by RuslanZavacky** [comment]
@BradWhittington yeap, I've installed it too, thx! :) I think you have to just create a separate repository (not a fork) and make a PR for changes in thumbor project itself, so people can find it :)

**Pull request closed without merging**
